[workspace]
authors = ["mzz <3108482097@qq.com>"]
channels = ["conda-forge"]
name = "pyTest"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"

[pypi-dependencies]
mylib = { path = "./mylib", editable = true }  # true表示修改包的代码立即生效